### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by a1dutch** [sett4/jackson-dataformat-xlsx-lite#19]
Hi,

Would you be able to deploy this to maven central?

instructions are here: https://central.sonatype.org/publish/requirements/

Cheers

@a1dutch

**Comment by sett4** [comment]
@a1dutch san
sorry for late reply.
i deployed to maven central. https://search.maven.org/artifact/com.github.sett4/jackson-dataformat-xlsx-lite/2.13.0/jar
