### ISSUE TITLE
Builder for XlsxMapper

### ISSUE THREAD

**Issue by Xxtreem** [sett4/jackson-dataformat-xlsx-lite#20]
Hi,
I need to disable MapperFeatures for may XlsxMapper but the disable() method ist deprecated since 2.13
Do you have plans to implement a builder?

```
     /**
     * @deprecated Since 2.13 use {@code JsonMapper.builder().disable(...)}
     */
    @Deprecated
    public ObjectMapper disable(MapperFeature... f) {
        _deserializationConfig = _deserializationConfig.without(f);
        _serializationConfig = _serializationConfig.without(f);
        return this;
    }

**Comment by sett4** [comment]
Hi @Xxtreem san.
How about #22
Which MapperFeature do you want to disable? If you let me know, I might add some tests.

**Comment by Xxtreem** [comment]
Hi @sett4,
Thank you! Looks good :)
I'm trying to disable the `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` of the `com.fasterxml.jackson.databind` package.

**Comment by sett4** [comment]
@Xxtreem san,
If you want to sort or unsort output column order, you can use `CsvSchema.sortedBy(...)`.

```java
        XlsxMapper xlsxMapper = new XlsxMapper();
        CsvSchema schema = xlsxMapper.schemaFor(Foo.class).withHeader().sortedBy("firstColumn", "secondColumn");
        xlsxMapper.writer(schema).writeValue(outputStream, foo);

```

**Comment by Xxtreem** [comment]
@sett4 I'm using a generic `renderXlsx` method so I can't sort by columnNames. 
For me its fine to simply disable the MapperFeature.

**Comment by sett4** [comment]
@Xxtreem san
I've depoyed #22  as 2.13.0-1 to Maven Central.
