### ISSUE TITLE
XlsxFactory using removed class in Jackson Dataformat CSV 2.15 

### ISSUE THREAD

**Issue by Xxtreem** [sett4/jackson-dataformat-xlsx-lite#24]
Hi,
When updating to Spring Boot version 3.1.0, which includes the new Jackson version 2.15.0,
I noticed that the class XlsxFactory imports a class that no longer exists.
```java
com.fasterxml.jackson.dataformat.csv.impl.CsvIOContext
``` 
Is a fix planned for the Jackson version 2.15.0?

**Comment by sett4** [comment]
Hi, Thank you for your contribution.
I've just released https://github.com/sett4/jackson-dataformat-xlsx-lite/releases/tag/2.15.2.
Artifacts are available on Maven Central.

**Comment by Xxtreem** [comment]
I’m glad to be of service 🫡
